"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-05-10 02:30:48.382886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=30), nullable=False),
    sa.Column('is_ai_suggested', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("owner_type IN ('giver_profile','taker_post')", name='ck_tags_owner_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('giver', 'taker')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giver_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio_short', sa.String(length=50), nullable=True),
    sa.Column('bio_long', sa.Text(), nullable=True),
    sa.Column('freechat_enabled', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('coffeechat_enabled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('mealchat_enabled', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.Column('coffeechat_price', sa.Integer(), server_default=sa.text('5000'), nullable=False),
    sa.Column('mealchat_price', sa.Integer(), server_default=sa.text('10000'), nullable=False),
    sa.Column('pricing_score', sa.Numeric(precision=3, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('pricing_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('match_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_newbie', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('taker_posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('preferred_format', sa.String(length=20), nullable=True),
    sa.Column('budget_min', sa.Integer(), nullable=True),
    sa.Column('budget_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('application_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('network','league','community','crew','circle','party')", name='ck_taker_posts_category'),
    sa.CheckConstraint("preferred_format IN ('freechat','coffeechat','mealchat')", name='ck_taker_posts_preferred_format'),
    sa.CheckConstraint("status IN ('open','matched','closed')", name='ck_taker_posts_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giver_experiences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('giver_profile_id', sa.UUID(), nullable=False),
    sa.Column('community_name', sa.String(length=100), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('max_member_count', sa.Integer(), nullable=True),
    sa.Column('proof_url', sa.Text(), nullable=True),
    sa.Column('achievement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['giver_profile_id'], ['giver_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('taker_id', sa.UUID(), nullable=False),
    sa.Column('giver_id', sa.UUID(), nullable=False),
    sa.Column('taker_post_id', sa.UUID(), nullable=True),
    sa.Column('initiated_by', sa.String(length=10), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('preferred_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('freechat','coffeechat','mealchat')", name='ck_matches_format'),
    sa.CheckConstraint("initiated_by IN ('taker','giver')", name='ck_matches_initiated_by'),
    sa.CheckConstraint("status IN ('pending','accepted','rejected','paid','completed','cancelled')", name='ck_matches_status'),
    sa.ForeignKeyConstraint(['giver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['taker_post_id'], ['taker_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # PRD §7: categories ARRAY 도메인 CHECK
    op.execute(
        "ALTER TABLE giver_experiences "
        "ADD CONSTRAINT ck_giver_experiences_categories "
        "CHECK (categories <@ ARRAY['network','league','community','crew','circle','party']::text[])"
    )

    # PRD §7: 검색용 인덱스
    op.execute(
        "CREATE INDEX idx_giver_categories ON giver_experiences USING GIN (categories)"
    )
    op.execute(
        "CREATE INDEX idx_posts_text ON taker_posts "
        "USING GIN (to_tsvector('simple', title || ' ' || body))"
    )
    op.create_index(
        "idx_posts_status_created",
        "taker_posts",
        ["status", sa.text("created_at DESC")],
    )
    op.create_index("idx_tags_owner", "tags", ["owner_type", "owner_id"])
    op.create_index("idx_tags_value", "tags", ["tag"])
    op.create_index("idx_matches_taker_status", "matches", ["taker_id", "status"])
    op.create_index("idx_matches_giver_status", "matches", ["giver_id", "status"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_matches_giver_status", table_name="matches")
    op.drop_index("idx_matches_taker_status", table_name="matches")
    op.drop_index("idx_tags_value", table_name="tags")
    op.drop_index("idx_tags_owner", table_name="tags")
    op.drop_index("idx_posts_status_created", table_name="taker_posts")
    op.execute("DROP INDEX IF EXISTS idx_posts_text")
    op.execute("DROP INDEX IF EXISTS idx_giver_categories")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('giver_experiences')
    op.drop_table('taker_posts')
    op.drop_table('giver_profiles')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
